name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest

    outputs:
      modules: ${{ steps.set-changed-files-output.outputs.modules }}
    
    name: Test changed-files
    
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get all test, doc and modules files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v38
        with:
          separator: ","
          dir_names: true
          files_yaml: |
            modules:
              - modules/**
          
      - name: Print if modules file(s) change
        id: print-changed-files-output
        
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `modules_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.modules_any_changed == 'true'  
        run: |
          echo "One or more modules file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.modules_all_changed_files }}"

      - name: Set output if modules file(s) change
        id: set-changed-files-output
        
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `modules_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files-yaml.outputs.modules_any_changed == 'true'  
        run: echo "modules=${{ steps.changed-files-yaml.outputs.modules_all_changed_files }}" >> $GITHUB_OUTPUT

  docs:

    runs-on: ubuntu-latest

    needs: changed_files

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ${{ needs.changed_files.outputs.modules }}
        output-file: README.md
        output-method: inject
        git-push: "true"

